### ISSUE TITLE
Missing file wavelets/WaveletUtils.swift

### ISSUE THREAD

**Issue by lucaji** [flaviostutz/piano-tuna#1]
Hi, I am very intrigued by the use of inharmonicity in pitch detection techniques - thanks for sharing the project along with the PDF "Octaves and inharmonicity in piano tuning". Any chance the missing file `WaveletUtils.swift` could be restored in order to build and play with the code?

TIA,
Luca

**Comment by flaviostutz** [comment]
Wow... there were lots of things that weren't commited. Glad I could find my localhost workspace here!
I've just commited the files. If you need any help making this run, please contacte me!

**Comment by flaviostutz** [comment]
inharmonicity is not used for "pitch detection". It is used later on for establishing the best note frequency adjustment for a good psicoacoutics perception due to the instrument inharmonicity characteristics. I got there. I started creating some sort of multiple string pitch detection so that I could tune my piano without having to mute sibiling strings for each note (a laborious task). Hope you can help if possible!

**Comment by lucaji** [comment]
Thank you for the updated commit (the build was ok after that) and the precisation :)
In the past I have tuned an old piano by ear and armed with some reference tones and heaps of patience I remember putting mutes and dampening cloth to control sympathetic resonating strings, and could eventually restore the overall tuning to an enjoyable level.
Definitely was not a task for the faint of heart, where a professional tuner would be advisable :P
Unfortunately I do not possess an acoustic piano but it will be cool to experiment with your project!
Cheers, Luca
